name: Lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Check code style
        run: npm run lint -- --max-warnings 0

      - name: Check formatting
        run: npx prettier . --check

      - name: Test build agent
        run: npm ci -w agent && npm run build -w agent

      - name: Test build app
        run: npm ci -w app && npm run build -w app
      # - name: Check clutter
      #   run: yarn knip

      # - name: Check that TypeScript compiles
      #   run: yarn tsc
